// <auto-generated />
using System;
using AzangaraMods_Website_Back.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AzangaraMods_Website_Back.Migrations
{
    [DbContext(typeof(MainDbContext))]
    [Migration("20260525093354_UserFlags")]
    partial class UserFlags
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AzangaraMods_Website_Back.Models.GalleryFile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("LevelId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LevelId");

                    b.ToTable("gallery_files");
                });

            modelBuilder.Entity("AzangaraMods_Website_Back.Models.Level", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AuthorId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(8192)
                        .HasColumnType("character varying(8192)");

                    b.Property<short>("Difficulty")
                        .HasColumnType("smallint");

                    b.Property<long?>("DiscordForumMessage")
                        .HasColumnType("bigint");

                    b.Property<long?>("DiscordForumThread")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastEdit")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("Published")
                        .HasColumnType("boolean");

                    b.Property<short>("RoomAmount")
                        .HasColumnType("smallint");

                    b.PrimitiveCollection<string[]>("Tags")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)[]");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("levels", t =>
                        {
                            t.HasCheckConstraint("CK_Tags_MaxCount", "array_length(\"Tags\",1) <= 10");
                        });
                });

            modelBuilder.Entity("AzangaraMods_Website_Back.Models.LevelFile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Downloads")
                        .HasColumnType("integer");

                    b.Property<string>("EntryPoint")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("FileSize")
                        .HasColumnType("integer");

                    b.Property<long>("LevelId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LevelId");

                    b.ToTable("level_files");
                });

            modelBuilder.Entity("AzangaraMods_Website_Back.Models.Token", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Secret")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("tokens");
                });

            modelBuilder.Entity("AzangaraMods_Website_Back.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Creation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Flags")
                        .HasColumnType("integer");

                    b.Property<bool>("HasProfilePicture")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("AzangaraMods_Website_Back.Models.GalleryFile", b =>
                {
                    b.HasOne("AzangaraMods_Website_Back.Models.Level", "Level")
                        .WithMany("GalleryFiles")
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Level");
                });

            modelBuilder.Entity("AzangaraMods_Website_Back.Models.Level", b =>
                {
                    b.HasOne("AzangaraMods_Website_Back.Models.User", "Author")
                        .WithMany("Levels")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("AzangaraMods_Website_Back.Models.LevelFile", b =>
                {
                    b.HasOne("AzangaraMods_Website_Back.Models.Level", "Level")
                        .WithMany("LevelFiles")
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Level");
                });

            modelBuilder.Entity("AzangaraMods_Website_Back.Models.Token", b =>
                {
                    b.HasOne("AzangaraMods_Website_Back.Models.User", "User")
                        .WithMany("Tokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AzangaraMods_Website_Back.Models.Level", b =>
                {
                    b.Navigation("GalleryFiles");

                    b.Navigation("LevelFiles");
                });

            modelBuilder.Entity("AzangaraMods_Website_Back.Models.User", b =>
                {
                    b.Navigation("Levels");

                    b.Navigation("Tokens");
                });
#pragma warning restore 612, 618
        }
    }
}
