export enum LevelDifficulties
{
    VeryEasy = 10,
    Easy = 20,
    Normal = 30,
    Hard = 40,
    VeryHard = 50,
    Expert = 60
}

export enum ErrorCodes {
    AuthLoginInvalid = 0x00,
    AuthRegisterUnknownError = 0x01,
    AuthLogoutNoChange = 0x02,
    DownloadLevelNotFound = 0x03,
    DownloadLevelRestricted = 0x04,
    DownloadLevelFileNotFound = 0x05,
    DownloadLevelFileUnsupportedType = 0x06,
    DownloadGalleryFileNotFound = 0x07,
    LevelGetNotFound = 0x08,
    LevelGetRestricted = 0x09,
    LevelPutNameTooLong = 0x0A,
    LevelPutNameTooShort = 0x0B,
    LevelPutDescriptionTooLong = 0x0C,
    LevelPutDescriptionTooShort = 0x0D,
    LevelPutTooManyTags = 0x0E,
    LevelPutTagTooLong = 0x0F,
    LevelEditNotYours = 0x10,
    LevelPatchNull = 0x11,
    LevelPatchNotFound = 0x12,
    LevelFilePutNull = 0x13,
    LevelFilePutPakTooBig = 0x14,
    LevelFilePutPakError = 0x15,
    LevelFilePutZipTooManyFiles = 0x16,
    LevelFilePutZipTooBig = 0x17,
    LevelFilePutInvalidFileType = 0x18,
    LevelFilePatchNull = 0x19,
    LevelFilePatchLevelNotFound = 0x1A,
    LevelFileDeleteNotFound = 0x1B,
    LevelFileDeleteLevelNotFound = 0x1C,
    LevelGalleryPutNull = 0x1D,
    LevelGalleryPutInvalidFileType = 0x1E,
    LevelGalleryDeleteNotFound = 0x1F,
    LevelGalleryDeleteLevelNotFound = 0x20,
    UserMeNotFound = 0x21,
    LevelFilePutZipError = 0x22,
    LevelFilePutPakWriteError = 0x23,
}